apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: game-stack-ingress
  namespace: game-stack-dev
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: game-stack.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: game-2048
            port:
              number: 80
