apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: monitoring-stack
  source:
    path: kubernetes/argocd-apps
    repoURL: git@github.com:raphaelmulenda/monitoring-stack.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true