apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eck-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: elastic-stack
    server: https://kubernetes.default.svc
  project: monitoring-stack
  source:
    path: kubernetes/apps/eck-stack
    repoURL: git@github.com:raphaelmulenda/monitoring-stack.git
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
