apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: game-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: monitoring-stack
  source:
    repoURL: git@github.com:raphaelmulenda/monitoring-stack.git
    targetRevision: HEAD
    path: kubernetes/apps/game-test/overlays/development
  destination:
    server: https://kubernetes.default.svc
    namespace: game-stack-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true