apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-operator-crds
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: monitoring-stack
  source:
    repoURL: git@github.com:raphaelmulenda/monitoring-stack.git
    targetRevision: HEAD
    path: kubernetes/apps/kube-prometheus/manifests/setup
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
