apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    app.kubernetes.io/instance: prometheus-operator-crds
    kubernetes.io/metadata.name: monitoring
    pod-security.kubernetes.io/warn: privileged
    pod-security.kubernetes.io/warn-version: latest
spec:
  finalizers:
    - kubernetes
status:
  phase: Active
