apiVersion: v1
kind: Service
metadata:
  name: game-2048
  namespace: game-stack-dev
spec:
  selector:
    app: game-2048
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
